version: "3.7"
services:
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-boot-iti-network
    restart: always
networks:
  spring-boot-iti-network:
    driver: bridge